site_name: r2u
site_url: https://github.com/eddelbuettel/r2u
docs_dir: src
site_dir: docs
copyright: Copyright &copy; 2022 - present Dirk Eddelbuettel
repo_url: https://github.com/eddelbuettel/r2u
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Lato
  favicon: assets/Rlogo.png
  logo: assets/Rlogo.svg

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eddelbuettel/r2u
      name: r2u on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eddelbuettel
      name: eddelbuettel on Twitter

nav:
  - Home:
    - index.md
  - Reference:
    - man/buildPackage.md
    - man/r2u-package.md
  - Articles:
    - FAQ: vignettes/FAQ.md
    - Notes: vignettes/Notes.md
  - News:
    - news.md
  - Changelog:
    - changelog.md
